mod: release # debug release
database:
  dialect: mysql # mysql postgresql sqllite
  url: mysip:Yangtao#123@tcp(192.168.1.192:13306)/mysip?charset=utf8&parseTime=True&loc=Local # 数据库地址
udp: 0.0.0.0:55060 # sip 服务器 udp 端口
tcp: 0.0.0.0:55060 # sip 服务器 tcp 端口
api: 0.0.0.0:8090 # sip 服务 restfulapi 端口
secret: z9hG4bK1233983766 # restful 接口验证 key 验证请求使用
logger: debug
jwt:
  token_expire: 7 # JWT Token 有效期（天），默认 7 天
media:
  restful: http://192.168.1.192:18080 # media 服务器 restfulapi 地址
  http: http://192.168.1.192:18080  # media 服务器 http 请求地址
  ws: ws://192.168.1.192:18080  # media 服务器 ws 请求地址
  rtmp: rtmp://192.168.1.192:1935  # media 服务器 rtmp 请求地址
  rtsp: rtsp://192.168.1.192:8554   # media 服务器 rtsp 请求地址
  rtp: http://192.168.1.192:10000  # media rtp 请求地址 zlm 对外开放的接受 rtp 推流的地址
  secret: KOKQ7jvwPlboCJFZq9l8SennShsSk6Ul # zlm secret key 用来请求 zlm 接口验证
stream:
  hls: 1 # 是否开启视频流转 hls
  rtmp: 1 # 是否开启视频流转 rtmp
gb28181: # gb28181 域，系统 id，用户 id，通道 id，用户数量，初次运行使用配置，之后保存数据库，如果数据库不存在使用配置文件内容
  lid:    33010000002000000001 # 系统 ID
  region: 3301000000           # 系统域
  did:    33010000001118       # 设备前缀
  cid:    33010000001318       # 通道前缀
  dnum:   0 # 设备 id = did + dnum
  cnum:   0 # 通道 id = cid + cnum
  pwd:    123456 # 默认设备接入密码
notify:
  devices_unknown: # 未知设备通知
  devices_active: # 设备活跃通知
  devices_regiest: #设备注册成功通知
  channels_active:  # 通道活跃通知

